"""Test the /trade wiring patches and verify they produce a working
integration of upstream hermes-agent 0.19.0 + TradeDesk.

This test:
1. Builds a fixture by copying upstream hermes-agent 0.19.0 files.
2. Copies the public package TradeDesk + trade_menu + positions_menu
   files into the fixture.
3. Applies the public package's hermes_overlay/patches/ patches to the
   upstream files.
4. Imports the patched adapter and verifies:
   - /trade command dispatch reaches trade_menu.handle_trade_command
   - tm: callback dispatch reaches trade_menu.handle_trade_callback
   - text dispatch reaches trade_menu.handle_trade_text
   - ordinary text falls through to the LLM path (no exception)

No network calls. No live trades.
"""
import os
import shutil
import subprocess
import sys
import tempfile
import urllib.request
import zipfile
import io
from pathlib import Path
from unittest.mock import MagicMock, AsyncMock

# === Constants ===
WHEEL_URL = "https://files.pythonhosted.org/packages/e5/30/c85be8290e9565dc3c7a9720e93f3e59e09b1b163487be4946c3aa848f80/hermes_agent-0.19.0-py3-none-any.whl"
PUB = Path(__file__).parent.parent  # hermes-tradedesk-public

# === Build the fixture ===
print("=== Building test fixture ===")
TMPDIR = Path(tempfile.mkdtemp(prefix="trade_wiring_test_"))
print(f"  fixture: {TMPDIR}")

# Layout
(TMPDIR / "hermes_cli").mkdir(parents=True)
(TMPDIR / "plugins" / "platforms" / "telegram" / "trade_menu").mkdir(parents=True)
(TMPDIR / "plugins" / "platforms" / "telegram" / "positions_menu").mkdir(parents=True)

# Download upstream.
wheel = "/tmp/hermes_agent-0.19.0.whl"
if not os.path.exists(wheel):
    urllib.request.urlretrieve(WHEEL_URL, wheel)
with zipfile.ZipFile(wheel) as zf:
    # The upstream wheel only has explicit __init__.py at:
    #   plugins/__init__.py
    #   plugins/platforms/telegram/__init__.py
    # `plugins/platforms/__init__.py` is an implicit namespace package and
    # is NOT in the wheel. We just create the directory.
    for member in [
        "hermes_cli/commands.py",
        "plugins/platforms/telegram/adapter.py",
        "plugins/platforms/telegram/telegram_ids.py",
        "plugins/platforms/telegram/telegram_network.py",
        "plugins/__init__.py",
        "plugins/platforms/telegram/__init__.py",
    ]:
        with zf.open(member) as src:
            target = TMPDIR / member
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(src.read())
        print(f"  copied upstream: {member}")
    # Create the implicit namespace package directory.
    (TMPDIR / "plugins" / "platforms").mkdir(parents=True, exist_ok=True)
    print("  created implicit namespace: plugins/platforms/")

# Copy public package files.
# Copy tradedesk (whole dir).
shutil.copytree(PUB / "tradedesk", TMPDIR / "tradedesk")

# Copy telegram overlay files individually (the destination dirs already
# exist from the upstream extraction).
for f in ("wizard.py",):
    shutil.copy(PUB / "hermes_overlay" / "telegram" / "trade_menu" / f,
                TMPDIR / "plugins" / "platforms" / "telegram" / "trade_menu" / f)
# trade_menu/__init__.py is generated by the install (or by the upstream).
# Use a minimal stub for testing.
(TMPDIR / "plugins" / "platforms" / "telegram" / "trade_menu" / "__init__.py").write_text(
    "from .wizard import handle_trade_command, handle_trade_text, handle_trade_callback\n"
    "__all__ = ['handle_trade_command', 'handle_trade_text', 'handle_trade_callback']\n"
)

# positions_menu: only the handlers are needed; the upstream may not have this
# package. Create a stub that mirrors our public package's structure.
(TMPDIR / "plugins" / "platforms" / "telegram" / "positions_menu").mkdir(exist_ok=True)
(TMPDIR / "plugins" / "platforms" / "telegram" / "positions_menu" / "__init__.py").write_text(
    "from .handlers import handle_positions_command, handle_positions_text, handle_positions_callback\n"
    "__all__ = ['handle_positions_command', 'handle_positions_text', 'handle_positions_callback']\n"
)
(TMPDIR / "plugins" / "platforms" / "telegram" / "positions_menu" / "handlers.py").write_text(
    "async def handle_positions_command(a, m): return False\n"
    "async def handle_positions_text(a, m): return False\n"
    "async def handle_positions_callback(a, q, d): return False\n"
)

shutil.copy(PUB / "hermes_overlay" / "telegram" / "shared_selectors.py",
            TMPDIR / "plugins" / "platforms" / "telegram" / "shared_selectors.py")
shutil.copy(PUB / "hermes_overlay" / "telegram" / "_positions_render.py",
            TMPDIR / "plugins" / "platforms" / "telegram" / "_positions_render.py")
print("  copied public package files (tradedesk, trade_menu, ...)")

# Apply patches.
result = subprocess.run(
    ["patch", "-p1", "-i", str(PUB / "hermes_overlay" / "patches" / "hermes_cli_commands.patch")],
    cwd=TMPDIR, capture_output=True, text=True,
)
print(f"  commands.patch: exit={result.returncode}, {result.stdout[:60]!r}")

result = subprocess.run(
    ["patch", "-p1", "-i", str(PUB / "hermes_overlay" / "patches" / "telegram_adapter.patch")],
    cwd=TMPDIR, capture_output=True, text=True,
)
print(f"  adapter.patch: exit={result.returncode}, {result.stdout[:60]!r}")

# === Run the tests ===
failures = []

# 1. Static checks on patched files.
print("\n=== Static checks ===")

text = (TMPDIR / "hermes_cli" / "commands.py").read_text()
if 'CommandDef("trade"' in text:
    print("  [PASS] commands.py has /trade CommandDef")
else:
    failures.append("commands.py missing /trade")
    print("  [FAIL] commands.py missing /trade")

if 'CommandDef("positions"' in text:
    print("  [PASS] commands.py has /positions CommandDef")
else:
    failures.append("commands.py missing /positions")
    print("  [FAIL] commands.py missing /positions")

adapter_text = (TMPDIR / "plugins" / "platforms" / "telegram" / "adapter.py").read_text()
if "_trade_menu_state" in adapter_text:
    print("  [PASS] adapter.py __init__ has _trade_menu_state")
else:
    failures.append("adapter.py missing _trade_menu_state")
    print("  [FAIL] adapter.py missing _trade_menu_state")

# Find _handle_callback_query and verify the trade dispatch.
def find_function(text, name):
    start = text.find(f"async def {name}")
    if start == -1:
        return ""
    end = text.find("\n    async def ", start + 1)
    if end == -1:
        end = text.find("\nclass ", start + 1)
    if end == -1:
        end = len(text)
    return text[start:end]

cb_text = find_function(adapter_text, "_handle_callback_query")
text_text = find_function(adapter_text, "_handle_text_message")
cmd_text = find_function(adapter_text, "_handle_command")

if "tm:" in cb_text and "handle_trade_callback" in cb_text:
    print("  [PASS] _handle_callback_query has tm: + handle_trade_callback")
else:
    failures.append("_handle_callback_query missing tm: dispatch")
    print("  [FAIL] _handle_callback_query missing tm: dispatch")

if "handle_trade_text" in text_text:
    print("  [PASS] _handle_text_message has handle_trade_text")
else:
    failures.append("_handle_text_message missing handle_trade_text")
    print("  [FAIL] _handle_text_message missing handle_trade_text")

if "handle_trade_command" in cmd_text:
    print("  [PASS] _handle_command has handle_trade_command")
else:
    failures.append("_handle_command missing handle_trade_command")
    print("  [FAIL] _handle_command missing handle_trade_command")

# 2. Runtime tests.
print("\n=== Runtime tests ===")
# Add the system hermes venv to PYTHONPATH for the heavy deps.
hermes_py_dir = "/usr/local/lib/hermes-agent/venv/lib/python3.11/site-packages"
sys.path.insert(0, hermes_py_dir)
sys.path.insert(0, str(TMPDIR))

# Mock the trade_menu module so the dispatches can be intercepted.
import types


def setup_adapter():
    """Build a minimal adapter instance and mock its helpers."""
    from plugins.platforms.telegram import adapter as adapter_mod
    TelegramAdapter = adapter_mod.TelegramAdapter
    adapter = TelegramAdapter.__new__(TelegramAdapter)
    adapter._trade_menu_state = {}
    adapter._positions_menu_state = {}
    return adapter, TelegramAdapter


# 2a. /trade command dispatch.
print("  2a. /trade command dispatch → trade_menu.handle_trade_command")
try:
    adapter, TelegramAdapter = setup_adapter()
    calls = []
    fake_tm = types.ModuleType("plugins.platforms.telegram.trade_menu")
    async def fake_command(adapter, msg):
        calls.append(("command", msg.text))
        return True
    fake_tm.handle_trade_command = fake_command
    fake_tm.handle_trade_text = lambda a, m: asyncio.sleep(0)
    fake_tm.handle_trade_callback = lambda a, q, d: asyncio.sleep(0)
    sys.modules["plugins.platforms.telegram.trade_menu"] = fake_tm
    fake_pm = types.ModuleType("plugins.platforms.telegram.positions_menu")
    fake_pm.handle_positions_command = lambda a, m: asyncio.sleep(0)
    fake_pm.handle_positions_text = lambda a, m: asyncio.sleep(0)
    fake_pm.handle_positions_callback = lambda a, q, d: asyncio.sleep(0)
    sys.modules["plugins.platforms.telegram.positions_menu"] = fake_pm
    # Mock helpers.
    adapter._is_user_authorized_from_message = lambda msg: True
    adapter._should_process_message = lambda msg, is_command=False: True
    adapter._should_observe_unmentioned_group_message = lambda msg: False
    adapter._observe_unmentioned_group_message = lambda *a, **k: None
    adapter._effective_update_message = lambda u: u.effective_message
    adapter._ensure_forum_commands = AsyncMock()
    adapter.handle_message = AsyncMock()
    adapter._build_message_event = lambda *a, **k: MagicMock()
    adapter._clean_bot_trigger_text = lambda t: t
    adapter._cache_replied_media = AsyncMock()
    adapter._apply_telegram_group_observe_attribution = lambda e: e
    adapter._enqueue_text_event = lambda e: None
    # Build fake message.
    msg = MagicMock(text="/trade", from_user=MagicMock(id=1), chat=MagicMock(id=1), message_thread_id=None)
    update = MagicMock(update_id=1, effective_message=msg, message=msg)
    import asyncio
    asyncio.run(TelegramAdapter._handle_command(adapter, update, None))
    if any(c[0] == "command" for c in calls):
        print("    [PASS] trade_menu.handle_trade_command was called")
    else:
        failures.append("2a. command dispatch did not call trade_menu")
        print("    [FAIL] command dispatch did not call trade_menu")
except Exception as e:
    failures.append(f"2a. exception: {e}")
    print(f"    [FAIL] {type(e).__name__}: {e}")

# 2b. tm: callback dispatch.
print("  2b. tm: callback dispatch → trade_menu.handle_trade_callback")
try:
    adapter, TelegramAdapter = setup_adapter()
    calls = []
    fake_tm = types.ModuleType("plugins.platforms.telegram.trade_menu")
    async def fake_cb(adapter, query, data):
        calls.append(("cb", data))
        return True
    fake_tm.handle_trade_callback = fake_cb
    sys.modules["plugins.platforms.telegram.trade_menu"] = fake_tm
    fake_pm = types.ModuleType("plugins.platforms.telegram.positions_menu")
    async def fake_pcb(adapter, query, data):
        calls.append(("pcb", data))
        return True
    fake_pm.handle_positions_callback = fake_pcb
    sys.modules["plugins.platforms.telegram.positions_menu"] = fake_pm
    query = MagicMock(data="tm:cancel", from_user=MagicMock(id=1),
                      message=MagicMock(chat_id=1, chat=MagicMock(type="private"),
                                       message_thread_id=None))
    query.answer = AsyncMock()
    update = MagicMock(update_id=1, callback_query=query)
    import asyncio
    asyncio.run(TelegramAdapter._handle_callback_query(adapter, update, None))
    if any(c[0] == "cb" for c in calls):
        print("    [PASS] trade_menu.handle_trade_callback was called")
    else:
        failures.append("2b. callback dispatch did not call trade_menu")
        print("    [FAIL] callback dispatch did not call trade_menu")
except Exception as e:
    failures.append(f"2b. exception: {e}")
    print(f"    [FAIL] {type(e).__name__}: {e}")

# 2c. text dispatch (wizard active).
print("  2c. wizard text dispatch → trade_menu.handle_trade_text")
try:
    adapter, TelegramAdapter = setup_adapter()
    key = "1:1"
    adapter._trade_menu_state = {key: {"awaiting": "quantity"}}
    calls = []
    fake_tm = types.ModuleType("plugins.platforms.telegram.trade_menu")
    async def fake_text(adapter, msg):
        calls.append(("text", msg.text))
        return True
    fake_tm.handle_trade_text = fake_text
    sys.modules["plugins.platforms.telegram.trade_menu"] = fake_tm
    fake_pm = types.ModuleType("plugins.platforms.telegram.positions_menu")
    fake_pm.handle_positions_text = lambda a, m: asyncio.sleep(0)
    sys.modules["plugins.platforms.telegram.positions_menu"] = fake_pm
    adapter._is_user_authorized_from_message = lambda msg: True
    adapter._should_process_message = lambda msg: True
    adapter._should_observe_unmentioned_group_message = lambda msg: False
    adapter._observe_unmentioned_group_message = lambda *a, **k: None
    adapter._effective_update_message = lambda u: u.effective_message
    adapter._ensure_forum_commands = AsyncMock()
    adapter._build_message_event = lambda *a, **k: MagicMock()
    adapter._clean_bot_trigger_text = lambda t: t
    adapter._cache_replied_media = AsyncMock()
    adapter._apply_telegram_group_observe_attribution = lambda e: e
    adapter._enqueue_text_event = lambda e: None
    msg = MagicMock(text="0.5", from_user=MagicMock(id=1), chat=MagicMock(id=1), message_thread_id=None)
    update = MagicMock(update_id=1, effective_message=msg, message=msg)
    import asyncio
    asyncio.run(TelegramAdapter._handle_text_message(adapter, update, None))
    if any(c[0] == "text" for c in calls):
        print("    [PASS] trade_menu.handle_trade_text was called")
    else:
        failures.append("2c. text dispatch did not call trade_menu")
        print("    [FAIL] text dispatch did not call trade_menu")
except Exception as e:
    failures.append(f"2c. exception: {e}")
    print(f"    [FAIL] {type(e).__name__}: {e}")

# 2d. ordinary text falls through to LLM (no wizard active).
print("  2d. ordinary text (no wizard) → LLM path")
try:
    adapter, TelegramAdapter = setup_adapter()
    adapter._trade_menu_state = {}  # empty
    fake_tm = types.ModuleType("plugins.platforms.telegram.trade_menu")
    async def fake_text(adapter, msg):
        return False  # No wizard consumed it
    fake_tm.handle_trade_text = fake_text
    sys.modules["plugins.platforms.telegram.trade_menu"] = fake_tm
    fake_pm = types.ModuleType("plugins.platforms.telegram.positions_menu")
    async def fake_ptext(adapter, msg):
        return False
    fake_pm.handle_positions_text = fake_ptext
    sys.modules["plugins.platforms.telegram.positions_menu"] = fake_pm
    enqueue_calls = []
    adapter._is_user_authorized_from_message = lambda msg: True
    adapter._should_process_message = lambda msg: True
    adapter._should_observe_unmentioned_group_message = lambda msg: False
    adapter._observe_unmentioned_group_message = lambda *a, **k: None
    adapter._effective_update_message = lambda u: u.effective_message
    adapter._ensure_forum_commands = AsyncMock()
    adapter._build_message_event = lambda *a, **k: MagicMock(text="event")
    adapter._clean_bot_trigger_text = lambda t: t
    adapter._cache_replied_media = AsyncMock()
    adapter._apply_telegram_group_observe_attribution = lambda e: e
    adapter._enqueue_text_event = lambda e: enqueue_calls.append(e)
    msg = MagicMock(text="ordinary text", from_user=MagicMock(id=1), chat=MagicMock(id=1), message_thread_id=None)
    update = MagicMock(update_id=1, effective_message=msg, message=msg)
    import asyncio
    asyncio.run(TelegramAdapter._handle_text_message(adapter, update, None))
    if len(enqueue_calls) > 0:
        print("    [PASS] ordinary text reached LLM path (enqueue called)")
    else:
        failures.append("2d. ordinary text did not reach LLM")
        print("    [FAIL] ordinary text did not reach LLM")
except Exception as e:
    failures.append(f"2d. exception: {e}")
    print(f"    [FAIL] {type(e).__name__}: {e}")

# === Final ===
print()
print("=" * 60)
if failures:
    print(f"FAILED: {len(failures)} checks failed")
    for f in failures:
        print(f"  - {f}")
    sys.exit(1)
else:
    print("ALL CHECKS PASSED")
    print("  - /trade and /positions CommandDef entries present")
    print("  - _trade_menu_state initialized")
    print("  - _handle_command dispatches to trade_menu.handle_trade_command")
    print("  - _handle_callback_query dispatches to trade_menu.handle_trade_callback on tm:")
    print("  - _handle_text_message dispatches to trade_menu.handle_trade_text when wizard active")
    print("  - ordinary text falls through to LLM path")
    print()
    print("The /trade wiring is reachable end-to-end through the patched adapter.")
    print("No live HTTP calls were made. No trades were placed.")

# Cleanup.
shutil.rmtree(TMPDIR, ignore_errors=True)
